### ISSUE TITLE
An instance installed with pipsi fails

### ISSUE THREAD

**Issue by funkyfuture** [telota/quick-csr#1]
an instance of the tool that has been installed with `pipsi` fails when invoked with this traceback:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/quick-csr", line 11, in <module>
    load_entry_point('quick-csr==0.0.0', 'console_scripts', 'quick-csr')()
  File "/home/user/.local/venvs/quick-csr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/.local/venvs/quick-csr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/home/user/.local/venvs/quick-csr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/home/user/.local/venvs/quick-csr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'quick_csr'
```

an invokation in a manually activated virtual environment works as expected.

**Comment by funkyfuture** [comment]
this is still reproducable after another installation.

the trick may be to install it with `pipsi install -e .` as this results in a working instance. if users can reproduce this i'll open a bug report. cc @schnoepf

**Comment by funkyfuture** [comment]
the recommended way to distribute the tool is as Python ZIP Applications now.
