### ISSUE TITLE
Installation nicht unter Python 3.5+ möglich

### ISSUE THREAD

**Issue by derYork** [telota/quick-csr#13]
Ich habe versucht die Anwendung zum laufen zu bekommen. Leider bekomme ich einen Fehler.
System: Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-140-generic x86_64)
Python: python3 --version - Python 3.5.2

`Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "quick-csr-linux-x86_64-0.2.pyz/__main__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "quick-csr-linux-x86_64-0.2.pyz/_bootstrap/__init__.py", line 64
    return root / f"{name}_{build_id}"
                                     ^
SyntaxError: invalid syntax`

Da ich weiß, dass es auf einem SYSTEM mit Python 3.6 durchläuft nehme ich an, dass es nicht mit Python 3.5+ funnktioniert. Weiterhin wird im Netz eine ähnlich Problematik mit dem "f-string" in einem anderen Zusammenhang beschrieben: 

> Ahh yeah, I am using f-strings there. Those came out in Python 3.6.

[ https://github.com/yngtodd/hyperspace/issues/18](url)

Wenn das so ist, sollte die readme hier 

> With Python 3.5+ installed, quick-csr can be run on any system by executing an appropriate Python ZIP Application that includes all its dependencies and system specific binaries.

angepasst werden.

Oder habe ich da irgendwas übersehen?

**Comment by funkyfuture** [comment]
da liegst du ganz richtig, solche bug reports kann man sich nur wünschen. gut ist immer auch zu wissen, wie die software bezogen, ggf. installiert und aufgerufen wurde.

besser wäre es wohl, die f-strings nach Python 3.5 zurück zu portieren. vielleicht hat @lpodl dafür mal zeit?

**Comment by derYork** [comment]
Danke für die Rückmeldung. Und nun die hoffentlich Vollständigen Infos.

System: Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-140-generic x86_64)
Python: python3 --version - Python 3.5.2

Ich habe folgendes Script auf den Server geladen
https://github.com/telota/quick-csr/releases/quick-csr-linux-x86_64-0.2.py

und wie folgt in meinem home-verzeichnis zum testen aufgerufen:
`python3 quick-csr-linux-x86_64-0.2.pyz www.example.de`

Dort liegt auch die Datei:
.quick-csr.cfg
mit folgendem Inhalt:
>[default]
organizationalUnitName = web department
organizationName = example
localityName = Berlin
stateOrProvinceName = Berlin
countryName = DE

**Comment by funkyfuture** [comment]
ein os-upgrade würde dir also auch helfen. :-D

 > Dort liegt auch die Datei: .quick-csr.cfg

aber:

> which is per default looked up as .quick-csr.cfg in your user directory 

es gehört also nach `~/.quick-csr.cfg`

**Comment by derYork** [comment]
Ja, ein OS-Upgrade würde mir helfen. Das ist auch nicht das Problem.
Ich werde eine Lösung finden um Python 3.6 nutzen zu können. Ich wollte nur darauf hinweisen, dass die Readme-Datei missverständlich ist. Es könnte anderen Usern Zeit sparen, wenn Sie es erst garnicht mit Python 3.5+ versuchen. 

Sorry, eventuell etwas unklar.
Bei mir ist mein Home-Verzeichnis die user directory `~/`
