### ISSUE TITLE
Key Error: Country Name

### ISSUE THREAD

**Issue by lpodl** [telota/quick-csr#3]
An error occurs after installing quick-csr in an venv, setup with virtualenv.
Using Python 3.6.5
What I did was:

```
pip install .
pip install -e .
quick-csr www.example.org
```

Complete error message:

```
`(test2) λ quick-csr www.example.org
Generating Certificate Signing Request and private key with these options:

key_size               :  4096
target_folder          :  C:\Users\Me\Projekte\quick-csr\quick-csr-master
commonName             :  www.example.org
alternativeNames       :  ./.

An unhandled exception occurred, please report this bug:
Traceback (most recent call last):
  File "c:\users\Me\projekte\quick-csr\quick-csr-master\quick_csr\cli.py", line 133, in main
    process(plan)
  File "c:\users\Me\projekte\quick-csr\quick-csr-master\quick_csr\cli.py", line 113, in process
    request = generate_request(plan)
  File "c:\users\Me\projekte\quick-csr\quick-csr-master\quick_csr\cli.py", line 84, in generate_request
    setattr(subject, key, plan[key])
KeyError: 'countryName'`
```

**Comment by funkyfuture** [comment]
thanks for reporting, could you please amend the content of the config file you used?

**Comment by lpodl** [comment]
I did use the default one:
```
    [default]

    organizationalUnitName = web department
    organizationName = Center For Universal Bauhaus Studies
    localityName = Tel Aviv
    stateOrProvinceName = Tel Aviv
    countryName = IL
```
However I misplaced it into the folder of the repository. 
Everything worked fine once I fixed that ;)
